namespace CellularAutomata.Cells;

public enum CellColor : byte
{
    Empty = 0,
    Solid = 1,
    GoldenSand = 2,
    DesertGold = 3,
    Wheatfield = 4,
    SaharaDune = 5,
    HoneyBeige = 6,
    ToastedAlmond = 7,
    AmberGrain = 8,
    ClayOchre = 9,
    GoldenWheat = 10,
    SunlitSandstone = 11,
    CoolBlue = 12,
    OceanBlue = 13,
    DeepSky = 14,
    CrystalLake = 15,
    SurfBlue = 16,
    BlueCurrent = 17,
    SplashBlue = 18,
    AzureDrift = 19,
    Wavestone = 20,
    RippleBlue = 21,
    SnowWhite = 22,      
    FrostTint = 23,      
    IceGrey = 24,        
    PaleSnow = 25,       
    BlueShadow = 26,     
    GlacialGlow = 27,    
    MorningFrost = 28,   
    PowderWhite = 29,    
    SilverMist = 30,     
    ArcticLight = 31,    
    IceBlue = 32,
    FrostBlue = 33,
    CrystalBlue = 34,
    PaleGlacier = 35,
    WinterSky = 36,
    SnowReflection = 37,
    DeepFreeze = 38,
    ArcticMist = 39,
    IcyHorizon = 40,
    GentleBlizzard = 41,
    SoftPlum = 42,           
    SmokyLavender = 43,      
    DustyMauve = 44,         
    PaleOrchid = 45,         
    MistyViolet = 46,        
    AshRose = 47,            
    TwilightGrey = 48,       
    MoonShadow = 49,         
    FadedLilac = 50,         
    DeepHeather = 51,  
}